apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
            - name: ENVIRONMENT
              value: {{ .Values.env.ENVIRONMENT }}
            - name: LOG_LEVEL
              value: {{ .Values.env.LOG_LEVEL }}

